---
name: Deploy static content to Pages

on:
  push:
    branches: ["develop"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  actions: read

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        id: setup-pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        id: upload-artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './'

      - name: Deploy to GitHub Pages
        id: deploy-pages
        uses: actions/deploy-pages@v4
